# Generated by Django 4.0.1 on 2022-02-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=20, null=True),
        ),
    ]
