# Generated by Django 4.0.1 on 2022-01-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Select',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='weeklymenu', to='meals.Menu'),
        ),
    ]
