# Generated by Django 4.0.1 on 2022-02-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_open',
        ),
        migrations.AlterField(
            model_name='menu',
            name='Day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
