# Generated by Django 4.0.1 on 2022-02-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_menu_is_open_alter_menu_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
