# Generated by Django 4.0 on 2022-02-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
